### ISSUE TITLE
'Endpoint' object has no attribute 'readable'

### ISSUE THREAD

**Issue by iAmGroute** [iAmGroute/NPTpy#11]
After some stress testing:
```
...................
1604087477.8 [00000031] Listener:        NewConnection    ()
1604087477.8 [00000000] Loop:            Enqueue          (22,)
1604087477.8 [00000000] Loop:            Running          (22, 'main Listener:49')
1604087477.8 [000000FB] Endpoint:        [Log created]
1604087477.8 [000000FB] Endpoint:        Inited           (7, -1)
1604087477.8 [00000000] Loop:            NewFuture        ()
1604087477.8 [00000000] Loop:            Paused           (22, 'main Listener:50, requestChannel Link:221, requestChannel Channels:100, requestNewChannel ControlEndpoint:67')
.
1604087477.9 [000000EA] Connector:       Error            (ConnectionResetError(104, 'Connection reset by peer'),)
1604087477.942 [Portal.Link    ]	Connection lost, reason: Closed by other end
1604087477.943 [Portal.Link    ]	Reconnecting
1604087477.9 [00000000] Loop:            Enqueue          (28,)
1604087477.9 [00000000] Loop:            Running          (28, 'reconnect Link:165')
1604087477.9 [0000002A] Link:            Disconnect       ()
1604087477.9 [00000000] Loop:            RunError         (AttributeError("'Endpoint' object has no attribute 'readable'"),)
..
1604087483.0 [00000000] Loop:            Enqueue          (23,)
1604087483.0 [00000000] Loop:            Running          (23, 'requestCloseChannel ControlEndpoint:136')
1604087483.0 [00000000] Loop:            RunError         (CancelledError(),)
.
1604087485.7 [00000000] Loop:            Enqueue          (26,)
1604087485.7 [00000000] Loop:            Running          (26, 'requestKA Portal:244')
1604087485.7 [00000000] Loop:            Finished         (26, None)
1604087485.8 [00000000] Loop:            Enqueue          (1,)
1604087485.8 [00000000] Loop:            Running          (1, 'rtask Portal:167, recvPacketAsync AsyncConnectorPacketized:30, bufferAsync AsyncConnectorPacketized:19, tryRecvAsync AsyncConnector:93, recvAsync AsyncConnector:84, wait AsyncConnector:16')
1604087485.8 [00000000] Loop:            NewFuture        ()
1604087485.8 [00000000] Loop:            Paused           (1, 'rtask Portal:167, recvPacketAsync AsyncConnectorPacketized:30, bufferAsync AsyncConnectorPacketized:19, tryRecvAsync AsyncConnector:93, recvAsync AsyncConnector:84, wait AsyncConnector:16')
..
1604087490.8 [00000000] Loop:            Enqueue          (13,)
1604087490.8 [00000000] Loop:            Running          (13, 'requestCloseChannel ControlEndpoint:136')
1604087490.8 [00000000] Loop:            RunError         (CancelledError(),)
.1604087495.781 [root]	'NoneType' object has no attribute 'socket'
Traceback (most recent call last):
  File "portal.main.py", line 38, in <module>
    p.main()
  File "/home/pi/git/NPTpy/NPTpy/Portal/Portal.py", line 56, in main
    Globals.runReminders()
  File "/home/pi/git/NPTpy/NPTpy/Globals.py", line 12, in runReminders
    kaReminderTX.run()
  File "/home/pi/git/NPTpy/NPTpy/Common/TimedReminder.py", line 13, in run
    Reminder.run(self)
  File "/home/pi/git/NPTpy/NPTpy/Common/Reminder.py", line 24, in run
    delegate.run()
  File "/home/pi/git/NPTpy/NPTpy/Common/Reminder.py", line 56, in run
    if f is not None: f(owner)
  File "/home/pi/git/NPTpy/NPTpy/Portal/Link.py", line 195, in handleRemindTX
    self.channels.sendKA()
  File "/home/pi/git/NPTpy/NPTpy/Portal/Channels.py", line 55, in sendKA
    self.epControl.sendKA()
  File "/home/pi/git/NPTpy/NPTpy/Portal/ControlEndpoint.py", line 54, in sendKA
    self.send(b'.', True)
  File "/home/pi/git/NPTpy/NPTpy/Portal/ControlEndpoint.py", line 23, in send
    self.parent.send(self.formMessage(data), untracked)
  File "/home/pi/git/NPTpy/NPTpy/Portal/Channels.py", line 52, in send
    self.myLink.send(data, untracked)
  File "/home/pi/git/NPTpy/NPTpy/Portal/Link.py", line 269, in send
    self.conRT.socket.settimeout(5)
AttributeError: 'NoneType' object has no attribute 'socket'
```
Caused by e89c4b7 ?
